[package]
name = "review-protocol"
version = "0.1.2"
edition = "2021"

[features]
client = ["quinn", "serde"]
server = ["quinn", "serde"]

[dependencies]
anyhow = "1"
oinq = { git = "https://github.com/petabi/oinq.git", tag = "0.11.0" }
quinn = { version = "0.10", optional = true }
semver = "1"
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
lazy_static = "1"
quinn = "0.10"
rcgen = "0.12"
rustls = "0.21"
tokio = { version = "1", features = ["macros", "rt"] }
