[package]
name = "review-protocol"
version = "0.1.1"
edition = "2021"

[features]
client = ["quinn", "serde"]
server = ["quinn", "serde"]

[dependencies]
anyhow = "1"
oinq = { git = "https://github.com/petabi/oinq.git", tag = "0.10.0" }
quinn = { version = "0.10", optional = true }
serde = { version = "1", optional = true }
